#!/usr/bin/env bash
# Configure domain name zone and create subdomain that points to the load-balance

get_record_info() {
	local domain="$1"
	local subdomain="$2"

	if [[ -z "$subdomain" ]]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
		record_type=$(dig +short "$sub"."$domain" | awk 'NR==1{print $4}')
		destination=$(dig +short "$sub"."$domain" | awk 'NR==1{print $1}')

		if [[ -n "$record_type" && -n "$destination" ]]; then
			echo "The subdomain $sub is a $record_type record and points to $destination"
		fi
	done
}
get_record_info "$@"
