#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

input="/etc/passwd"
while IFS= read -r line
do
	username=$(echo "$line" | cut -d':' -f1)
	userid=$(echo "$line" | cut -d':' -f3)
	homedir=$(echo "$line" | cut -d':' -f6)
	echo "$username:$userid:$homedir"
done < "$input"
