#!/usr/bin/env bash
server {
    # Listen on port 80
    listen      80 default_server;
    listen      [::]:80 default_server ipv6only=on;

    # Use server IP as domain name
    server_name 54.162.90.117;

    # Customize HTTP response header
    add_header  X-Served-By 192765-web-01;

    # Serve / route on AirBnB_clone_v4
    location / {
        proxy_pass http://127.0.0.1:5003;
    }

    # Serve /static/ route on AirBnB_clone_v4
    location /static {
    }

    # 404 error page
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
